### ISSUE TITLE
Docbook: Filename in beginning of list of references 

### ISSUE THREAD

**Issue by hcf-n** [michal-h21/make4ht#28]
When converting the following MWE with make4ht to docbook the list of the references is preceded by a verbatim filename from det current xml file.

\documentclass{article}
\usepackage[style=authoryear-comp]{biblatex}
\addbibresource{\jobname.bib}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{key,
  author = {Author, A.},
  year = {2001},
  title = {Title},
  publisher = {Publisher},
}
\end{filecontents}

\begin{document}
\cite{key}
\printbibliography
\end{document}

I named the original file mwe.tex. 
When i remove  <link xlink:href="mwe.xml"/> from the resulting mwe.xml file, I get the expected result.

Best regards
Hans Christian

**Comment by michal-h21** [comment]
I think the main issue here is that TeX4ht doesn't contain configuration for BibLaTeX bibliography in the Docbook output, so you get HTML tags instead. I've fixed that in the sources. You can try attached `docbook.4ht` file.

[docbook.zip](https://github.com/michal-h21/make4ht/files/4809242/docbook.zip)

**Comment by hcf-n** [comment]
I tried the attached file, but still get an extra link. In the MWE above the resulting xml file from make4ht contains an <link xlink:href="mwe.xml"/> that I think shouldn't be there.

**Comment by michal-h21** [comment]
Ah, I see. Try this version.

[docbook.zip](https://github.com/michal-h21/make4ht/files/4818688/docbook.zip)

**Comment by hcf-n** [comment]
Works fine. Thank you!
